### ISSUE TITLE
Do you have a timeline in mind for releasing the code?

### ISSUE THREAD

**Issue by crazyofapple** [CRIPAC-DIG/NGNN#1]
Hi,

This work seems really interesting, great!

I'm looking forward to learning from codes, but it seems that it's still unavailable.

Do you think you can give us some idea about when it'll be made available?

Thanks!

**Comment by cyente** [comment]
i have upload a temporal version for all of yours present needs. The better version of code will be released before 12/05 (the date of the web conference)

**Comment by donghaoye** [comment]
@cyente any new version?
